---
apiVersion: v1
kind: Namespace
metadata:
  name: {{namespace}}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{namespace}}-pvdata
  labels:
    app: {{namespace}}-pvdata
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{nfs-fabric-data-path}}
    server: {{nfs-server}}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 namespace: {{namespace}}
 name: {{namespace}}-pvdata
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 10Gi
 selector:
   matchLabels:
     app: {{namespace}}-pvdata

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: {{namespace}}
  name: zookeeper
spec:
  serviceName: zkheadless
  selector:
    matchLabels:
      app: hyperledger
      role: zookeeper
      ns: {{namespace}}
  replicas: 3
  template:
    metadata:
      labels:
       app: hyperledger
       role: zookeeper
       ns: {{namespace}}
    spec:
      containers:
        - name: zookeeper
          image: hyperledger/fabric-zookeeper
          env:
            - name: ZOO_SERVERS
              value: "server.1=zookeeper-0.zkheadless:2888:3888 server.2=zookeeper-1.zkheadless:2888:3888 server.3=zookeeper-2.zkheadless:2888:3888"
            - name: ZOO_TICK_TIME
              value: "2000"
            - name: ZOO_INIT_LIMIT
              value: "10"
            - name: ZOO_SYNC_LIMIT
              value: "2"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/bash"
                  - "-c"
                  - |
                    sed -i "s/${HOSTNAME}\.[^:]*:/0.0.0.0:/g" /conf/zoo.cfg
                    echo $((${HOSTNAME##*-}+1)) > /data/myid
---
apiVersion: v1
kind: Service
metadata:
   namespace: {{namespace}}
   name: zkheadless
spec:
 selector:
   app: hyperledger
   role: zookeeper
   ns: {{namespace}}
 clusterIP: None
 ports:
   - name: server
     protocol: TCP
     port: 2888
   - name: leader-election
     protocol: TCP
     port: 3888
   - name: client
     protocol: TCP
     port: 2181